name = "omnibackend2"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# ---------- Shared vars (non-secret) ----------
[vars]
ENVIRONMENT = "development"
FRONTEND_URL = "http://localhost:3000"
WORKER_BASE_URL = "https://omnibackend2.fweago-flavaz.workers.dev"

# ---------- Development ----------
[env.development.vars]
ENVIRONMENT = "development"
FRONTEND_URL = "http://localhost:3000"

# ---------- Production ----------
[env.production.vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://omni2-8d2.pages.dev"

# ---- D1 Database binding ----
[[d1_databases]]
binding = "DB"
database_name = "omnidb"
database_id = "014dc18a-e6cc-4efd-85d6-97434f1d994e"
# preview_database_id = "..."

# ---- R2 bucket for audio ----
[[r2_buckets]]
binding = "AUDIO_STORAGE"
bucket_name = "fwea-audio-files"
# preview_bucket_name = "..."

# ---- Workers AI binding ----
[ai]
binding = "AI"

# ---- KV (optional) ----
[[kv_namespaces]]
binding = "CACHE"
id = "427859929f0b4b63b3b1c1376eb5b798"
# preview_id = "..."

# ---- Analytics Engine ----
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "omni_analytics"

# ---- Durable Objects ----
# (Removed because the class is not defined in your code)
# [[durable_objects.bindings]]
# name = "PROCESSING_STATE_V2"
# class_name = "ProcessingStateV2"
# [[migrations]]
# tag = "v1"
# new_classes = ["ProcessingStateV2"]

# ---- Build / triggers ----
[build]
command = ""

[triggers]
crons = ["0 2 * * *", "0 0 * * SUN"]

[placement]
mode = "smart"
